# Advanced Completion Training Configuration
# Enables distillation and budget consistency features

model:
  visual_dim: 256
  tactile_dim: 128
  fusion_dim: 192
  latent_dim: 64
  num_coarse_gaussians: 128
  num_refined_gaussians: 2048

training:
  num_epochs: 50
  batch_size: 4
  gradient_accumulation_steps: 8
  learning_rate: 1e-4
  weight_decay: 1e-5
  mixed_precision: true
  gradient_checkpointing: true
  
  # Budget curriculum settings
  budget_mode: "mixture"  # or "curriculum"
  budget_schedule:
    0: [1]           # epochs 0-5: only K=1
    5: [3, 5]        # epochs 5-15: K={3,5}  
    15: [1, 3, 5, 10, 20, 50, 100]  # epochs 15+: all budgets
  budget_sampling_weights:
    low: 0.4   # K=1,3
    mid: 0.4   # K=5,10,20
    high: 0.2  # K=50,100,ALL
  
  # Loss gating and weighting
  gate_appearance_to_feelsight: true
  tactile_loss_real_weight: 1.0
  tactile_loss_pseudo_weight: 0.3
  
  # ADVANCED FEATURES (the key additions!)
  distillation_enabled: true
  distillation_weight: 0.1
  consistency_enabled: true
  consistency_weight: 0.05
  
  # Loss weights
  chamfer_weight: 1.0
  constraint_weight: 0.5
  kl_weight: 0.1
  appearance_weight: 0.05
  tactile_weight: 1.0
  normal_regularizer_weight: 0.1  # Enable normal regularizer

datasets:
  # Multi-dataset training with both FeelSight and ShapeNet
  primary_dataset: "multi"
  dataset_config:
    shapenet:
      data_path: "/home/krishi/gaussianfeels/data/ShapeSplatsV1"
      enabled: true
      num_points: 2048
      # Budget mapping for ShapeNet (emulates FeelSight budgets via occlusion ratios)
      budgets: [1, 3, 5, 10, 20, 50, 100]
      pseudo_tactile_contacts: 128
    feelsight_occlusion:
      data_path: "/home/krishi/gaussianfeels/data/feelsight_occlusion"
      enabled: true
      # Uses precomputed partials from scripts/precompute_fused_partials.py
      budgets: [1, 3, 5, 10, 20, 50, 100]
      sampling_weights: [0.15, 0.15, 0.15, 0.15, 0.15, 0.15, 0.10]
  
  # Sampling ratios between datasets
  sampling_ratios:
    shapenet: 0.70          # 70% synthetic ShapeNet  
    feelsight_occlusion: 0.30  # 30% real FeelSight data

memory:
  num_workers: 2
  pin_memory: false
  prefetch_factor: 2
  persistent_workers: false

validation:
  validation_frequency: 100
  save_frequency: 500
  early_stopping_patience: 10
  metrics_f1_ratio: 0.02
  metrics_normalize_points: true

experiment:
  experiment_dir: "experiments"
  tensorboard_enabled: true
  save_sample_outputs: true
  log_level: "INFO"

# Optional: Teacher model path for distillation
# teacher_checkpoint: "experiments/teacher_model/best_model.pt"