# @package _global_
defaults:
  - override /hydra/hydra_logging: none
  - override /hydra/job_logging: none

main:
  touch_depth:
    _target_: null
    mode: vit
    weights: null  # Will be set dynamically based on real vs sim
    
    settings: 
      real: 
        blend_sz: 0
        border: 0
        ratio: 1.2 # multiplier to decide the contact threshold. Set higher to reduce false positives
        clip: 10 # sets all heightmap outputs < clip pix to zero. Set higher to reduce noisy predictions
        batch_size: 1
        bg_id: null

      sim: 
        blend_sz: 0
        border: 0
        ratio: 0 # multiplier to decide the contact threshold. Set higher to reduce false positives
        clip: 5 # sets all heightmap outputs < clip pix to zero. Set higher to reduce noisy predictions
        batch_size: 1
        bg_id: 10

    General:
        device: cuda
        type: depth
        model_timm: vit_small_patch16_224.dino
        emb_dim: 384
        hooks: [2, 5, 8, 11]
        read: projection
        resample_dim: 128
        optim: adam
        lr_backbone: 1e-5
        lr_scratch: 1e-4
        loss_depth: mse
        loss_segmentation: ce
        momentum: 0.9
        epochs: 500
        batch_size: 50
        path_model: data/tactile_transformer
        path_input_images: data/tacto_data/004_sugar_box/00/tactile_images
        path_predicted_images: output
        seed: 0
        patch_size: 16

    Dataset:
        paths:
            path_dataset: input
            list_datasets: [
                "002_master_chef_can",
                "003_cracker_box",
                "007_tuna_fish_can",
                "008_pudding_box",
                "009_gelatin_box",
                "010_potted_meat_can",
                "011_banana",
                "012_strawberry",
                "013_apple",
                "014_lemon",
                "015_peach",
                "016_pear",
                "017_orange",
                "018_plum",
                "019_pitcher_base",
                "024_bowl",
                "026_sponge",
                "029_plate",
                "030_fork",
                "031_spoon",
                "032_knife",
                "033_spatula",
                "036_wood_block",
                "040_large_marker",
                "044_flat_screwdriver",
                "050_medium_clamp",
                "051_large_clamp",
                "052_extra_large_clamp",
                "053_mini_soccer_ball",
                "054_softball",
                "056_tennis_ball",
                "057_racquetball",
                "058_golf_ball",
                "061_foam_brick",
                "062_dice",
                "065-a_cups",
                "065-b_cups",
                "070-a_colored_wood_blocks",
                "072-a_toy_airplane",
                "077_rubiks_cube"]
            path_images: tactile_images
            path_segmentations: gt_contactmasks
            path_depths: gt_heightmaps
        extensions:
            ext_images: .jpg
            ext_segmentations: .jpg
            ext_depths: .jpg
        splits:
            split_train: 0.6
            split_val: 0.2
            split_test: 0.2
        transforms:
            resize: [224, 224]
            p_flip: 0.0
            p_crop: 0.0
            p_rot: 0.0
        classes:
            "1":
                name: contact
                color: 255
    wandb:
        enable: true
        username: suddhu
        images_to_show: 5
        im_h: 640
        im_w: 480

hydra:
  mode: RUN
  run:
    dir: .
  sweep:
    dir: .
    subdir: .
  launcher:
    _target_: hydra._internal.BasicLauncher
  sweeper:
    _target_: hydra._internal.BasicSweeper
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      ${hydra.help.footer}'
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers: [console]
    loggers:
      hydra:
        level: INFO
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers: [console]
    disable_existing_loggers: false
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra: []
    task: []
  job:
    name: tactile_only_test
    override_dirname: ''
    id: ???
    num: ???
    config_name: main/touch_depth/touchvit
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.1'
    cwd: /home/krishi/gfs2
    config_sources:
    - path: hydra.conf
      provider: hydra
    - path: /home/krishi/gfs2/misc/configs
      provider: main
    - path: structured://
      provider: schema
    choices:
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: none
      hydra/hydra_logging: none
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false